services:
  dev-backend:
    container_name: dev-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    # https://docs.docker.com/compose/file-watch/
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - ./backend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 5001:5001
    # expose:
    #   - 5001
