services:
  prod-db:
    image: ${DB_IMG}
    # command: 공식 이미지를 사용하는데, 이미지에 명세이 이미 있다.
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web-proxy-server

  prod-be:
    depends_on:
      - prod-db
    image: ${BE_IMG}
    command: npm run prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      BE_PORT: ${BE_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      DB_DATABASE: ${DB_DATABASE}
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
    expose:
      - ${BE_PORT}
    networks:
      - web-proxy-server

  prod-fe:
    depends_on:
      - prod-be
    image: ${FE_IMG}
    command: serve -s dist -l ${VITE_FE_PORT}
    restart: unless-stopped
    environment:
      VITE_FE_PORT: ${VITE_FE_PORT}
    expose:
      - ${VITE_FE_PORT}
    networks:
      - web-proxy-server

volumes:
  db-data:
networks:
  web-proxy-server:
    external: true
