services:
  dev-db:
    container_name: dev-db
    build:
      context: ../DB/
      dockerfile: Dockerfile.dev
    # command: 공식 이미지를 사용하는데, 이미지에 명세이 이미 있다.
    restart: unless-stopped
    env_file:
      - ./env/.env.DB.dev
    expose:
      - 3306
    develop:
      watch:
        - action: rebuild
          path: ../DB/

  dev-backend:
    depends_on:
      - dev-db
    container_name: dev-backend
    build:
      context: ../backend/
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    env_file:
      - ./env/.env.backend.dev
    ports:
      - 5001:5001
    # client server가 뚫리면 바꿔주자.
    # expose:
    #   - 5001
    # https://docs.docker.com/compose/file-watch/
    develop:
      watch:
        - action: sync
          path: ../backend/
          target: /app/
          ignore:
            - ../backend/node_modules
